name: Atualizar frase do README

on:
  schedule:
    - cron: "*0 0 * * *"  # a cada minuto
  workflow_dispatch:       # permite disparar manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v3
        with:
          ref: main           

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Instalar dependências
        run: pip install --upgrade pip

      - name: Rodar script de atualização
        run: python update_readme.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md quotes.txt
          git diff --cached --quiet || git commit -m "🔄 chore: update daily quote"
          git push
